name: NoCure
main: prevent.curing.NoCure
version: '1.2.1'
api-version: '26.2'
author: Arkterion Labs
website: https://arkterion.com
description: Prevents players from curing zombie villagers
softdepend:
  - DiscordSRV
